version: "3"

services:
  db:
    build:
      context: "./db"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
      
  nats:
    image: nats-streaming:latest
    restart: always
    depends_on:
      - db
    command: -m 8222 --store SQL --sql_driver mysql --sql_source "root:pwd@tcp(db:3306)/nss_db"
    ports:
      - "4222"
      - "8222:8222"

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "3030:3030"
    depends_on:
      - db
      - nats

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "3131:3131"
    depends_on:
      - db
      - nats